# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP 346 G3\OneDrive\Documents\DP21PYDS5\database\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editTitle = QtWidgets.QLineEdit(self.centralwidget)
        self.editTitle.setGeometry(QtCore.QRect(10, 40, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.editTitle.setFont(font)
        self.editTitle.setText("")
        self.editTitle.setObjectName("editTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 97, 23))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 10, 63, 23))
        self.label_2.setObjectName("label_2")
        self.editRating = QtWidgets.QSpinBox(self.centralwidget)
        self.editRating.setGeometry(QtCore.QRect(460, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.editRating.setFont(font)
        self.editRating.setSuffix("")
        self.editRating.setPrefix("")
        self.editRating.setMaximum(10)
        self.editRating.setProperty("value", 5)
        self.editRating.setObjectName("editRating")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(550, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setDefault(False)
        self.btnSave.setFlat(False)
        self.btnSave.setObjectName("btnSave")
        self.bookList = QtWidgets.QLabel(self.centralwidget)
        self.bookList.setGeometry(QtCore.QRect(10, 80, 621, 361))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.bookList.setFont(font)
        self.bookList.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.bookList.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.bookList.setObjectName("bookList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Book Title</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Rating</span></p></body></html>"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.bookList.setText(_translate("MainWindow", "Book List to be Loaded Here"))
